spring.application.name=play_with_ai_backend
server.port=${PORT:8080}

# Chu?i k?t n?i chu?n cho Spring Boot:
spring.mongodb.uri=mongodb+srv://trietl_39_79:12345@cluster0.qncmtbb.mongodb.net/chat_db?retryWrites=true&w=majority&appName=Cluster0